global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aquabill-api"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["localhost:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["localhost:9121"]
